### ISSUE TITLE
Realy Bad Perfomance

### ISSUE THREAD

**Issue by moulin-louis** [spacemeowx2/ldn_mitm#45]
Hi,
I'm try to play with my friends to Super Smash Bros Ultimate but were lagging a lot. We have 1Gb/s connection both and with Mario Kart 8, the game run perfect.
Thx for help.

Sorry for my english, i'm french

**Comment by spacemeowx2** [comment]
Latency and bandwidth are not the same.
1Gb/s doesn't mean you have no zero between the server and you and the server and your friend. And MK8 requires little on latency.

**Comment by moulin-louis** [comment]
Yes, I understand that but our pc is connected by ethernet, we using french servers and 
we stand 50 centimeters from our internet box.  And SSBU is not a little slow, it is unplayable. So i cant understand how i can make this better. But otherwise thank you for your quick response!

**Comment by spacemeowx2** [comment]
* use 5Ghz wifi on Switch(less interference than 2.4Ghz)
* change the server you connecting to(maybe the server is slow)

**Comment by moulin-louis** [comment]
We were already at 5ghz so tomorrow I will test to change the server (02h00 AM here). Thx for your help and I tell you again tomorrow

**Comment by moulin-louis** [comment]
Hello, I tried with the same conditions but by changing the server. The results are the same, SSBU is unplayable. Thx for your help

**Comment by spacemeowx2** [comment]
maybe it's a issue about lan-play. What OS are you using? and the version of lan-play is?

**Comment by moulin-louis** [comment]
We are both on Windows 10 with the latest version of switch-lan-play. We use switch-lan-gui, maybe we should tried without.

**Comment by moulin-louis** [comment]
I did not specify but with the latest version of ldn-mitn

**Comment by Slluxx** [comment]
## I know this topic is old but for you and anyone else looking this up in the future:

The performance issues you have (especially in MK8 vs SSBU) are due to the different networking protocols the games are using: **TCP & UDP**. UDP is your average protocol, used in anything where _speed is more important than reliability_, for example video streaming. UDP sends networking packages that can arrive in the wrong order, double or not at all. If in a video one frame out of thousands has a little hickup in form of an artifact, you dont really notice or care about it.

TCP is used in anything where _reliability is top priority_. To ensure this, the application demands for the packets in order and if they are not, it will wait for them to be resend before continuing to process them.

You may have guessed it by now. MK8 uses UDP and SSBU uses TCP. Now you could argue why the heck they chose a protocol that lags. The answer is simple. In a game like SSBU, you dont want any kind of inaccuracy. It is important that any input you do is absolute precise and not just interpolated and guessed by the game if your or your opponents connection is bad. In MK8 it doesnt really matter at what frame you got hit by a blue shell, but SSBU players need frame perfect accuracy.

BTW: Usually the player with the worst connection "dictates" the lag. Dont play with more people than you have to in a loby or try to fix your ping if you can. **The speed of your connection, as long as you dont have a 500kb/s connection, doesnt really matter at all.**
